describe('Home To Patient Registration', () => {
  it('Should Navigate To Patient Register', () => {
    cy.visit('/')
    cy.get('h1').contains('Connect with top Rated Doctors')
    cy.get('a[href*="/patient/login"]').eq(0).click()
    cy.get('h3').contains('Explore the future with us.')
    cy.get('a[href*="/patient/register"]').eq(0).click()
  })
})

describe('Patient Registration Form', () => {
  it('Should Fill And Register With The Correct Information', () => {
    cy.visit('patient/register')
    cy.get('#name').type('Harold')
    cy.get('#name').should('have.value', 'Harold')
    cy.get('#email').type('harold@gmail.com')
    cy.get('#email').should('have.value', 'harold@gmail.com')
    cy.get('#password').type('password')
    cy.get('#password').should('have.value', 'password')
    cy.get('#phoneNumber').type('+44 20 1234 5678')
    cy.get('#phoneNumber').should('have.value', '+44 20 1234 5678')
    cy.get('#address').type('123 Main Street')
    cy.get('#address').should('have.value', '123 Main Street')
    cy.get('#dateOfBirth').type('1994-08-04')
    cy.get('#dateOfBirth').should('have.value', '1994-08-04')
    cy.get('#male').click()
    cy.get('#male').should('be.checked')
    cy.get('#profilePicture').selectFile('client/public/imnotperfectimawesome.jpg', { subjectType: 'input' })
    cy.get('#profilePicture').should('have.value','C:\\fakepath\\imnotperfectimawesome.jpg', { subjectType: 'input' })
    cy.get('#bloodType').type('AB-')
    cy.get('#bloodType').should('have.value', 'AB-')
    cy.get('#allergies').type('Manual Labour')
    cy.get('#allergies').should('have.value', 'Manual Labour')
    cy.get('#medications').type('Whiskey Does Help')
    cy.get('#medications').should('have.value', 'Whiskey Does Help')
    cy.get('#surgicalHistory').type('I Dont Know A Broken Bone I Guess')
    cy.get('#surgicalHistory').should('have.value', 'I Dont Know A Broken Bone I Guess')
    cy.get('#familyMedicalHistory').type('None')
    cy.get('#familyMedicalHistory').should('have.value', 'None')
    cy.get('#submit-register').click()
  })
})